version: '2'

services:
    mysql:
        container_name: '${SITE_NAME}_mysql'
        image: 'wexample/mysql:${WEX_IMAGES_VERSION}'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            - ${SITE_PATH_ROOT}/mysql/data:/var/lib/mysql
            - ${SITE_PATH_ROOT}/mysql/dumps:/var/www/dumps
            - ${SITE_PATH_ROOT}/tmp:/var/www/tmp
            # Issue with : [Warning] World-writable config file ... ignored
            # - ${CONF_WEB_MYSQL_CNF}:/etc/mysql/conf.d/my.cnf:ro
        networks:
          - tmp_wex_net