version: '2'

services:
    dolibarr:
      container_name: ${SITE_NAME_INTERNAL}_dolibarr
      restart: always
      image: tuxgasy/dolibarr:${DOLIBARR_VERSION}
      stdin_open: true
      tty: true
      environment:
        - VIRTUAL_HOST=${DOMAIN_MAIN}
        # Database
        - DOLI_DB_HOST=${MYSQL_DB_HOST}
        - DOLI_DB_NAME=${MYSQL_DB_NAME}
        - DOLI_DB_USER=${MYSQL_DB_USER}
        - DOLI_DB_PASSWORD=${MYSQL_DB_PASSWORD}
        - DOLI_URL_ROOT=http://0.0.0.0
        - PHP_INI_DATE_TIMEZONE='Europe/Paris'
      networks:
        - tmp_wex_net
