version: '2'

services:
    wordpress:
        container_name: '${SITE_NAME}_wordpress'
        image: 'wexample/wordpress'
        restart: always
        networks:
          - tmp_wex_net
        volumes:
          - ${SITE_PATH_ROOT}wordpress/config:/var/www/html/wp-content/config
          - ${SITE_PATH_ROOT}wordpress/.htaccess:/var/www/html/.htaccess:ro
          - ${SITE_PATH_ROOT}wordpress/backups:/var/www/html/wp-content/backups
          - ${SITE_PATH_ROOT}wordpress/languages:/var/www/html/wp-content/languages
          - ${SITE_PATH_ROOT}wordpress/plugins:/var/www/html/wp-content/plugins
          - ${SITE_PATH_ROOT}wordpress/themes:/var/www/html/wp-content/themes
          - ${SITE_PATH_ROOT}wordpress/themes-child:/var/www/html/wp-content/themes-child
          - ${SITE_PATH_ROOT}wordpress/uploads:/var/www/html/wp-content/uploads
        environment:
          # Site env
          - WEX_SITE_ENV=${SITE_ENV}
          - VIRTUAL_HOST=${SITE_NAME}.wex
          # Database
          - MYSQL_DB_HOST=${MYSQL_DB_HOST}
          - MYSQL_DB_NAME=${MYSQL_DB_NAME}
          - MYSQL_DB_USER=${MYSQL_DB_USER}
          - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}

