version: '2'

services:
    mariadb:
        container_name: '${SITE_NAME_INTERNAL}_mariadb'
        image: mariadb:10.3.6
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MARIADB_DB_PASSWORD}
            - MYSQL_DATABASE=${MARIADB_DB_NAME}
            - MYSQL_USER=${MARIADB_DB_USER}
            - MYSQL_PASSWORD=${MARIADB_DB_PASSWORD}
        volumes:
            - ${SITE_PATH_ROOT}/mariadb/data:/var/lib/mysql
            - ${CONF_MY_MARIADB_CNF}:/etc/mysql/conf.d/site.cnf
        networks:
          - tmp_wex_net
