version: '2'

services:
    mastodon:
        container_name: '${SITE_NAME}_mastodon'
        image: 'tootsuite/mastodon:${MASTODON_VERSION}'
        restart: always
        env_file: .env.production
        command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
        # healthcheck:
        #       test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy=off localhost:3000/api/v1/instance || exit 1"]
        networks:
          - tmp_wex_net
        volumes:
          - ./mastodon/system:/mastodon/public/system
        ports:
          - "127.0.0.1:3000:3000"

    streaming:
        container_name: '${SITE_NAME}_streaming'
        image: 'tootsuite/mastodon:${MASTODON_VERSION}'
        restart: always
        env_file: .env.production
        command: yarn start
        # healthcheck:
        #       test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy=off localhost:${SERVICE_PORT_MASTODON}1/api/v1/streaming/health || exit 1"]
        ports:
          - "${SERVICE_PORT_MASTODON}1:3000"
        networks:
          - tmp_wex_net

    sidekiq:
        container_name: '${SITE_NAME}_sidekiq'
        image: 'tootsuite/mastodon:${MASTODON_VERSION}'
        restart: always
        env_file: .env.production
        command: bundle exec sidekiq
        # healthcheck:
        #       test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --proxy=off localhost:${SERVICE_PORT_MASTODON}2/api/v1/streaming/health || exit 1"]
        ports:
          - "${SERVICE_PORT_MASTODON}2:4000"
        volumes:
          - ./mastodon/system:/mastodon/public/system
        networks:
          - tmp_wex_net
