networks:
  tmp_wex_net:
    external: true
services:
  network_mysql:
    container_name: network_mysql
    environment:
      MYSQL_DATABASE: network
      MYSQL_PASSWORD: ncdkjscnkscnjscnsdlkcndslk
      MYSQL_ROOT_PASSWORD: ncdkjscnkscnjscnsdlkcndslk
      MYSQL_USER: root
    image: wexample/mysql:latest
    networks:
      tmp_wex_net: null
    restart: always
    volumes:
    - sites/network/mysql/my.cnf:/etc/mysql/conf.d/site.cnf:rw
    - sites/network/mysql/data:/var/lib/mysql:rw
    - sites/network/mysql/dumps:/var/www/dumps:rw
    - sites/network/tmp:/var/www/tmp:rw
  network_phpmyadmin:
    container_name: network_phpmyadmin
    environment:
      PMA_HOST: network_mysql
      PMA_PASSWORD: ncdkjscnkscnjscnsdlkcndslk
      PMA_USER: root
      VIRTUAL_HOST: pma.network.wex
    image: phpmyadmin/phpmyadmin:4.7.9-1
    links:
    - network_mysql
    networks:
      default: null
      tmp_wex_net: null
    restart: always
    volumes:
    - sites/network/php/phpmyadmin.ini:/etc/php/7.1/apache2/conf.d/99-wex.ini:rw
  network_web:
    build:
      context: sites/network
      dockerfile: ./docker/Dockerfile.web
    container_name: network_web
    environment:
      MYSQL_DB_HOST: network_mysql
      MYSQL_DB_NAME: network
      MYSQL_DB_PASSWORD: ncdkjscnkscnjscnsdlkcndslk
      MYSQL_DB_USER: root
      VIRTUAL_HOST: network.wex
      VIRTUAL_PORT: '80'
      WEX_SITE_ENV: local
    expose:
    - '80'
    image: network/web:latest
    networks:
      tmp_wex_net: null
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - /opt/wex_server/proxy/certs:/certs:rw
    - sites/network/apache/web.conf:/etc/apache2/sites-available/000-default.conf:rw
    - sites/network/php/web.local.ini:/etc/php/7.1/apache2/conf.d/99-wex.ini:rw
    - sites/scripts:/opt/wexample:rw
    - sites/network:/var/www/html:rw
    - sites/network/mysql/dumps:/var/www/mysql/dumps:rw
version: '2.0'

