version: '2'

services:
    redmine:
      container_name: ${SITE_NAME_INTERNAL}_redmine
      restart: always
      image:  redmine:3.4.6
      volumes:
        - ${SITE_PATH_ROOT}/redmine/configuration.yml:/usr/src/redmine/config/configuration.yml
        - ${SITE_PATH_ROOT}redmine/files:/usr/src/redmine/files
        - ${SITE_PATH_ROOT}redmine/data:/home/redmine/data
      environment:
        - VIRTUAL_HOST=${SITE_NAME}.wex
        - VIRTUAL_PORT=3000
        # Database
        - REDMINE_DB_MYSQL=${MYSQL_DB_HOST}
        - REDMINE_DB_DATABASE=${MYSQL_DB_NAME}
        - REDMINE_DB_USERNAME=${MYSQL_DB_USER}
        - REDMINE_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      networks:
        - tmp_wex_net