version: '2'

services:
    postgres:
        container_name: '${SITE_NAME}_postgres'
        image: postgres:11.1
        restart: always
        environment:
          - POSTGRES_DB=${POSTGRES_DB_NAME}
          - POSTGRES_USER=${POSTGRES_DB_USER}
          - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
          - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
          - ${SITE_PATH_ROOT}/postgres/data:/var/lib/postgresql/data
        networks:
          - tmp_wex_net