version: '2'

services:
    gitstats:
        container_name: ${SITE_NAME_INTERNAL}_gitstats
        image: wexample/gitstats:latest
        stdin_open: true
        tty: true
        restart: always
        hostname: ${DOMAIN_MAIN}
        volumes:
          - ${SITE_PATH_ROOT}project:/var/www/project
          - ${SITE_PATH_ROOT}reports:/var/www/reports
        environment:
          - VIRTUAL_HOST=${DOMAIN_MAIN}
          - VIRTUAL_PORT=80
        networks:
          - tmp_wex_net