version: '2'

services:
    phpmyadmin:
        container_name: '${SITE_NAME_INTERNAL}_phpmyadmin'
        image: phpmyadmin/phpmyadmin:4.7.9-1
        environment:
          - PMA_HOST=${SITE_NAME_INTERNAL}_mysql
        restart: always
        networks:
          - default
          - tmp_wex_net
        volumes:
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.1/apache2/conf.d/99-wex.ini
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.2/apache2/conf.d/99-wex.ini
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.3/apache2/conf.d/99-wex.ini
        user: ${USER_UID}