version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.7.0
    container_name: wex_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Certificates configuration
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      # Nginx configuration
      - ./nginx.conf:/etc/nginx/conf.d/wex.conf:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: nginx_proxy
    restart: always
    privileged: true
    networks:
      - wex_net

  proxy-certs:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.8.1
    container_name: wex_reverse_proxy_certs
    # DEBUG environment:
    #  - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/www/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    container_name: wex_reverse_proxy_entrypoint
    image: 'wexample/php7:${WEX_IMAGES_VERSION}'
    ports:
      - '99:80'
    stdin_open: true
    tty: true
    environment:
        # Displayed on main IP.
        - VIRTUAL_HOST=${WEX_DOCKER_MACHINE_IP}
    volumes:
       - ./entrypoint:/var/www/html
       - ${WEX_WEXAMPLE_DIR_TMP}:/tmp/wexample/
    networks:
      - wex_net

networks:
  wex_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

