version: '2'

services:
    wordpress5:
        container_name: '${SITE_NAME_INTERNAL}_wordpress5'
        image: wexample/wordpress5
        stdin_open: true
        tty: true
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=${SITE_NAME}.wex
            - VIRTUAL_PORT=80
            # Database
            - WORDPRESS_DB_HOST=${MYSQL_DB_HOST}
            - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
            - WORDPRESS_DB_USER=${MYSQL_DB_USER}
            - WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}
            - WORDPRESS_TABLE_PREFIX=${WP_DB_TABLE_PREFIX}
            #- WORDPRESS_DEBUG=1
            #- WORDPRESS_CONFIG_EXTRA=
        volumes:
            # Minimal env files.
            - ${SITE_PATH_ROOT}.wex:/var/www/.wex
            - ${SITE_PATH_ROOT}.env:/var/www/.env
            - ${SITE_PATH_ROOT}tmp:/var/www/tmp
            # Apache
            - ${CONF_WEB_APACHE_CONF}:/etc/apache2/sites-available/000-default.conf
            # Php
            - ${CONF_WEB_PHP_INI}:/usr/local/etc/php/conf.d/99-wex.ini
            # Mysql dumps
            - ${SITE_PATH_ROOT}mysql/dumps:/var/www/mysql/dumps
            # Wordpress
            - ${SITE_PATH_ROOT}wordpress/:/var/www/html
        networks:
            - tmp_wex_net

    # From : https://stackoverflow.com/a/51001043
    cli:
        container_name: '${SITE_NAME_INTERNAL}_cli'
        image: wordpress:cli-2.4.0
        # This is required to run cli with the same
        # user-id as wordpress. This way there are no permission problems
        # when running the cli
        user: xfs
        stdin_open: true
        tty: true
        environment:
            # Database
            - WORDPRESS_DB_HOST=${MYSQL_DB_HOST}
            - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
            - WORDPRESS_DB_USER=${MYSQL_DB_USER}
            - WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}
            - WORDPRESS_TABLE_PREFIX=${WP_DB_TABLE_PREFIX}
        volumes:
            # Wordpress
            - ${SITE_PATH_ROOT}wordpress/:/var/www/html
        networks:
            - tmp_wex_net
