version: '2'

services:
    sonarqube:
        container_name: '${SITE_NAME}_sonarqube'
        image: sonarqube:${SONARQUBE_VERSION}
        stdin_open: true
        tty: true
        restart: always
        expose:
            - 9000
        environment:
            - WEX_SITE_ENV=${SITE_ENV}
            - VIRTUAL_HOST=${DOMAINS}
            - VIRTUAL_PORT=80
            - SONARQUBE_JDBC_USERNAME=${POSTGRES_DB_USER}
            - SONARQUBE_JDBC_PASSWORD=${POSTGRES_DB_PASSWORD}
            - SONARQUBE_JDBC_URL=jdbc:postgresql://${POSTGRES_DB_NAME}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
        volumes:
            - ${SITE_PATH_ROOT}/sonarqube/conf:/opt/sonarqube/conf
            - ${SITE_PATH_ROOT}/sonarqube/data:/opt/sonarqube/data
            - ${SITE_PATH_ROOT}/sonarqube/logs:/opt/sonarqube/logs:rw
            - ${SITE_PATH_ROOT}/sonarqube/extensions:/opt/sonarqube/extensions:rw
        networks:
            - tmp_wex_net
