version: '2'

services:

    web:
        ports:
          - "80:80"
        volumes:
         # Use local wex scripts
         - ${WEX_SCRIPTS_PATH}:/opt/wexample

    phpmyadmin:
        # Avoid to type login / password on local
        environment:
          - PMA_USER=root
          - PMA_PASSWORD=${SITE_DB_PASSWORD}
