version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always
    privileged: true
    networks:
      - wex_net

  proxy-certs:
    image: jrcs/letsencrypt-nginx-proxy-companion
    # DEBUG environment:
    #  - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/www/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # https://github.com/tomav/docker-mailserver
  wex_mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    # TODO
    domainname: wexample.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /var/www/mail/mail:/var/mail
      - /var/www/mail/state:/var/mail-state
      - /var/www/mail/server/:/tmp/docker-mailserver/
    networks:
      - wex_net

networks:
  wex_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

