version: '2'

services:
    moodle:
        container_name: '${SITE_NAME_INTERNAL}_moodle'
        image: wexample/moodle:${WEX_IMAGES_VERSION}
        stdin_open: true
        tty: true
        expose:
            - 80
        environment:
            - MOODLE_URL=${SITE_NAME}.wex
            - VIRTUAL_HOST=${SITE_NAME}.wex
            # Database
            - MYSQL_DB_HOST=${MYSQL_DB_HOST}
            - MYSQL_DB_PORT=${MYSQL_DB_PORT}
            - MYSQL_DB_NAME=${MYSQL_DB_NAME}
            - MYSQL_DB_USER=${MYSQL_DB_USER}
            - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            # Minimal env files.
            - ${SITE_PATH_ROOT}.wex:/var/www/html/.wex
            - ${SITE_PATH_ROOT}.env:/var/www/html/.env
            - ${SITE_PATH_ROOT}.git:/var/www/html/.git
            - ${SITE_PATH_ROOT}moodle/data:/var/www/html/moodledata
            # Apache
            - ${CONF_MOODLE_APACHE_CONF}:/etc/apache2/sites-available/000-default.conf
            # Php
            - ${CONF_MOODLE_PHP_INI}:/etc/php/7.1/apache2/conf.d/99-wex.ini
            - ${CONF_MOODLE_PHP_INI}:/etc/php/7.2/apache2/conf.d/99-wex.ini
            - ${CONF_MOODLE_PHP_INI}:/etc/php/7.3/apache2/conf.d/99-wex.ini
            - ${CONF_MOODLE_PHP_INI}:/etc/php/7.4/apache2/conf.d/99-wex.ini
            # Mysql dumps
            - ${SITE_PATH_ROOT}mysql/dumps:/var/www/mysql/dumps
            # Share same wex scripts for all environments.
            - ${WEX_SCRIPTS_PATH}:/opt/wexample
            # Use common certificates storage
            - ${WEX_WEXAMPLE_DIR_PROXY}proxy/certs:/certs
            - ${SITE_PATH_ROOT}tmp:/var/www/html/tmp
        networks:
          - tmp_wex_net
