version: '2'

services:
    web:
        container_name: '${SITE_NAME}_web'
        image: 'wexample/php7:${WEX_IMAGES_VERSION}'
        stdin_open: true
        tty: true
        environment:
            - VIRTUAL_HOST=${SITE_NAME}.wex
            - VIRTUAL_PORT=${WEX_COMPOSE_PORT_1}
        volumes:
            # Site folder
            - ${SITE_PATH_ROOT}:/var/www/html
            # Apache
            - ${CONF_WEB_APACHE_CONF}:/etc/apache2/sites-available/000-default.conf
            # Php
            - ${CONF_WEB_PHP_INI}:/etc/php/7.1/apache2/conf.d/99-wex.ini
            # Cron
            - ${CONF_WEB_CRON}:/var/default.cron
            # Mysql dumps
            - ${SITE_PATH_ROOT}dumps:/var/dumps
            # Share same wex scripts for all environments.
            - ${WEX_SCRIPTS_PATH}:/opt/wexample
        networks:
            - reverseproxy_wex_net

