version: '2'

services:
    n8n:
      container_name: ${SITE_NAME_INTERNAL}_n8n
      restart: always
      image: n8nio/n8n:${N8N_VERSION}
      ports:
        - 5678:5678
      environment:
        - VIRTUAL_HOST=${DOMAIN_MAIN}
        - VIRTUAL_PORT=80
        - TIME_ZONE='Europe/Paris'
        # Database
        - PSM_AUTO_CONFIGURE=true
        - MYSQL_HOST=${MYSQL_DB_HOST}
        - MYSQL_DATABASE=${MYSQL_DB_NAME}
        - MYSQL_USER=${MYSQL_DB_USER}
        - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
      volumes:
        # Minimal env files.
        - ${SITE_PATH_ROOT}.n8n:/home/node/.n8n
      networks:
        - tmp_wex_net
