version: '2'

services:
    otra:
        container_name: '${SITE_NAME_INTERNAL}_otra'
        image: 'wexample/otra:${OTRA_VERSION}'
        stdin_open: true
        tty: true
        restart: always
        expose:
            - 80
        environment:
            - WEX_SITE_ENV=${SITE_ENV}
            - VIRTUAL_HOST=${DOMAINS}
            - VIRTUAL_PORT=80
            # Database
            - MYSQL_DB_HOST=${MYSQL_DB_HOST}
            - MYSQL_DB_NAME=${MYSQL_DB_NAME}
            - MYSQL_DB_USER=${MYSQL_DB_USER}
            - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            # Site folder
            - ${SITE_PATH_ROOT}:/var/www/html
            # Apache
            - ${CONF_WEB_APACHE_CONF}:/etc/apache2/sites-available/000-default.conf
            # Php
            - ${CONF_WEB_PHP_INI}:/etc/php/7.4/apache2/conf.d/99-wex.ini
            # Use common certificates storage
            - ${WEX_WEXAMPLE_DIR_PROXY}proxy/certs:/certs
        networks:
            - tmp_wex_net

