version: '2'

services:
    gitlab:
      container_name: ${SITE_NAME_INTERNAL}_gitlab
      restart: always
      image: gitlab/gitlab-ce:${GITLAB_VERSION}
      hostname: ${DOMAIN_MAIN}
      volumes:
        - ${SITE_PATH_ROOT}gitlab/backups:/var/opt/gitlab/backups
        - ${SITE_PATH_ROOT}gitlab/config:/etc/gitlab
        - ${SITE_PATH_ROOT}gitlab/logs:/var/log/gitlab
        - ${SITE_PATH_ROOT}gitlab/data:/var/opt/gitlab
      environment:
        - VIRTUAL_HOST=${DOMAIN_MAIN}
        - SMTP_DOMAIN=${DOMAIN_MAIN}
        - VIRTUAL_PORT=80
      networks:
        - tmp_wex_net