version: '2'

services:
    nextcloud:
        container_name: '${SITE_NAME}_nextcloud'
        image: nextcloud:15.0.4-apache
        restart: always
        environment:
          - VIRTUAL_HOST=${SITE_NAME}.wex
          - MYSQL_HOST=${SITE_NAME}_mariadb
          - MYSQL_DATABASE=${SITE_NAME}
          - MYSQL_USER=${MYSQL_DB_USER}
          - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            - ${SITE_PATH_ROOT}/nextcloud/data:/var/www/html
            - ${SITE_PATH_ROOT}/nextcloud/extra-addons:/mnt/extra-addons
        networks:
          - tmp_wex_net
