version: '2'

services:
    monitor:
      container_name: ${SITE_NAME_INTERNAL}_monitor
      restart: always
      image: scavin/phpservermonitor:${MONITOR_VERSION}
      ports:
        - 9090:9090
      environment:
        - VIRTUAL_HOST=${DOMAIN_MAIN}
        - VIRTUAL_PORT=80
        - TIME_ZONE='Europe/Paris'
        # Database
        - PSM_AUTO_CONFIGURE=true
        - MYSQL_HOST=${MYSQL_DB_HOST}
        - MYSQL_DATABASE=${MYSQL_DB_NAME}
        - MYSQL_USER=${MYSQL_DB_USER}
        - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
      networks:
        - tmp_wex_net