version: '2'

services:
    rocketchat:
        image: rocketchat/rocket.chat:0.63.3
        restart: unless-stopped
        container_name: ${SITE_NAME}_rocketchat
        environment:
          - VIRTUAL_HOST=rocket.${SITE_NAME}.wex
          - VIRTUAL_PORT=${SITE_PORT_RANGE}6
          - PORT=3000
          - ROOT_URL=http://rocket.${SITE_NAME}.wex
          - MONGO_URL=mongodb://mongo:27017/rocketchat
          - MONGO_OPLOG_URL=mongodb://mongo:27017/local
          - MAIL_URL=smtp://smtp.mailgun.org
        volumes:
          - ${SITE_PATH_ROOT}/uploads:/app/uploads
        networks:
          - reverseproxy_wex_net

    # this container's job is just run the command to initialize the replica set.
    # it will run the command and remove himself (it will not stay running)
    rocketchat_init:
        image: mongo:3.7.5-jessie
        command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
        networks:
          - reverseproxy_wex_net

    hubot:
        image: rocketchat/hubot-rocketchat:v1.0.11
        restart: unless-stopped
        environment:
          - ROCKETCHAT_URL=${SITE_NAME]_rocketchat:${SITE_PORT_RANGE}6
          - ROCKETCHAT_ROOM=GENERAL
          - ROCKETCHAT_USER=wex
          - ROCKETCHAT_PASSWORD=vchgdsvcghdvcdsjvcds
          - BOT_NAME=wex
          - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
        volumes:
          - ${SITE_PATH_ROOT}/hubot/scripts:/home/hubot/scripts
