version: '2'

services:
    redis:
        container_name: '${SITE_NAME}_redis'
        image: redis:4.0.9
        restart: always
        volumes:
            - ${SITE_PATH_ROOT}/redis/data:/var/lib/redis:Z
        networks:
          - tmp_wex_net
        command:
            - --loglevel warning