version: '2'

services:
    phpmyadmin:
        container_name: '${SITE_NAME}_phpmyadmin'
        image: phpmyadmin/phpmyadmin
        environment:
          - PMA_HOST=${SITE_NAME}_mysql
        restart: always
        networks:
          - reverseproxy_wex_net
        volumes:
            - ${CONF_PHPMYADMIN_PHP_INI}:/etc/php/7.1/apache2/conf.d/99-wex.ini
