version: '2'

# We use intensive files concatenation and service extensions
# in order to keep as possible a minimum of services definition in websites
# and let to pick and control expected container.
# See wexample::site/compose to see concatenation method detail.

networks:
  reverseproxy_wex_net:
    external: true
