version: '2'

services:
    mongo:
        container_name: '${SITE_NAME}_mongo'
        image: 'mongo:3.7.5-jessie'
        restart: always
        volumes:
            - ${SITE_PATH_ROOT}/mongo/data:/data/db
        command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1 --bind_ip_all --port ${SITE_PORT_RANGE}70
        networks:
          - reverseproxy_wex_net
