version: '2'

services:
    mariadb:
        container_name: '${SITE_NAME}_mariadb'
        image: mariadb:10.3.6
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${SITE_DB_PASSWORD}
            - MYSQL_DATABASE=${SITE_DB_NAME}
            - MYSQL_USER=${SITE_DB_USER}
            - MYSQL_PASSWORD=${SITE_DB_PASSWORD}
        volumes:
            - ${SITE_PATH_ROOT}/mariadb/data:/var/lib/mysql
        networks:
          - reverseproxy_wex_net
